apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-events-sa
  namespace: kubeflow

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argo-events-demo-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argo-events-cluster-role
subjects:
- kind: ServiceAccount
  name: argo-events-sa
  namespace: kubeflow

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argo-events-demo-cluster-role
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
